baseURL = 'https://about.ztmy.net/'
languageCode = 'zh-cn'
title = 'About AKMYAN'
theme = 'PaperMod'

[params]
  env = "production"
  description = "这是一个使用 Hugo 和 PaperMod 主题构建的示例网站"
  author = "AKMYAN"
  
  # 主页设置
  homeInfoParams.Title = "AKMYAN的杂谈"
  homeInfoParams.Content = "Connect the World"
  
  # 社交链接
  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/kazefujii"
  
  [[params.socialIcons]]
    name = "email"
    url = "mailto:me@ztmy.net"

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30
